In [ ]:
Universal Functions in array

In [2]:
import numpy as np

In [ ]:
#How we read the the file numpy

In [6]:
salaries =np.genfromtxt('salary.csv',delimiter=',')   #CSV--comma separated value

In [7]:
salaries

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [8]:
salaries.shape

(1147,)

In [ ]:
Wanted to apply statisal operation on top the file.

In [9]:
mean =np.mean(salaries)
median =np.median(salaries)
sd =np.std(salaries)
variance =np.var(salaries)

In [ ]:
# Alternate way of f strings

In [16]:
print('Mean =%i' %mean)
print('Median =%i' %Median)
print('standard Deviation =%i' %sd)
print('variance =%i' %variance)     # Case sensitive, observe 'Median'

Mean =55894


NameError: name 'Median' is not defined

In [15]:
print('Mean =%i' %mean)
print('Median =%i' %median)
print('Standard Deviation =%i' %sd)
print('Variance =%i' %variance)

Mean =55894
Median =48000
Standard Deviation =55170
Variance =3043770333


In [13]:
mean =np.mean(salaries)
median =np.median(salaries)
sd =np.std(salaries)
variance =np.var(salaries)

In [29]:
#Indeixng array

In [37]:
a =np.arange(11)*2


In [38]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [39]:
a[2]

4

In [40]:
a[-1]

20

In [41]:
#Slicing array

In [42]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [43]:
a[0:3]

array([0, 2, 4])

In [44]:
a[4:7]

array([ 8, 10, 12])

In [45]:
# Reversing of an array

In [46]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [49]:
a[::-1]

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

In [50]:
#Creating a dataset

In [55]:
Employees =np.array([['john', 'sam', 'david','chris'],
                    [1, 2, 3, 4],
                   [45000,55000,70000,85000]])

In [56]:
print(Employees)

[['john' 'sam' 'david' 'chris']
 ['1' '2' '3' '4']
 ['45000' '55000' '70000' '85000']]


In [59]:
Employees

array([['john', 'sam', 'david', 'chris'],
       ['1', '2', '3', '4'],
       ['45000', '55000', '70000', '85000']], dtype='<U5')

In [60]:
Employees(0)

TypeError: 'numpy.ndarray' object is not callable

In [61]:
Employees[0]

array(['john', 'sam', 'david', 'chris'], dtype='<U5')

In [62]:
Employees[1]

array(['1', '2', '3', '4'], dtype='<U5')

In [63]:
Employees[2]

array(['45000', '55000', '70000', '85000'], dtype='<U5')

In [64]:
# Req: Retrive david name on the outpu

In [65]:
Employees[0,2]

'david'

In [66]:
Employees[2,2]

'70000'

In [67]:
Employees[1,2],[0,2],[2,2]

('3', [0, 2], [2, 2])